[project]
name = "network_security"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "certifi>=2026.7.22",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "pymongo[srv]>=4.17.0",
    "python-dotenv>=1.2.2",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["network_security*"]
exclude = ["notebooks*", "Network_Data*"]
